// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvtfbmhhpypzzevsladf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dGZibWhocHlwenpldnNsYWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTA3MzEsImV4cCI6MjA3MTk2NjczMX0.dxcwlHjlUiyAX9l--h90O1xLOczJSn2nEAK0HhDevYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});